summary: A POC to validate bulk emails
value:
  fullscreen: true
  grid:
    - '12':
        fixed: false
        h: 10
        w: 8
        x: 2
        y: 0
      '3':
        fixed: false
        h: 1
        w: 1
        x: 1
        y: 1
      id: d
      data:
        id: d
        type: textcomponent
        actions: []
        componentInput:
          type: templatev2
          connections: []
          eval: "Email Verification Instructions\r\n\r\n1. Create a new Google Spreadsheet.\r\n2. In the first column (Column A), enter the email addresses you want to verify. Each email address should be in a separate row.\r\n   Example: https://docs.google.com/spreadsheets/d/1TXtZo4k0Jhygqbbsr75dTjTpRMP3qH5ewMpt1pqqbNI\r\n3. Make the spreadsheet publicly accessible:\r\n   - Click on the \"Share\" button in the top right corner of the spreadsheet.\r\n   - In the \"Share with others\" dialog, click on \"Change to anyone with the link\".\r\n   - Select \"Viewer\" as the access level.\r\n   - Click \"Done\" to save the sharing settings.\r\n4. Copy the URL of the publicly shared spreadsheet.\r\n5. Paste the spreadsheet URL into the input field below and click \"Verify Emails\"."
          fieldType: template
        configuration:
          copyButton:
            type: static
            value: false
          style:
            type: static
            value: Body
          tooltip:
            type: static
            value: ''
        customCss:
          container:
            class: ''
            style: ''
          text:
            class: ''
            style: ''
        horizontalAlignment: left
        verticalAlignment: top
    - '12':
        fixed: false
        h: 1
        w: 4
        x: 4
        y: 10
      '3':
        fixed: false
        h: 1
        w: 2
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: textinputcomponent
        actions: []
        configuration:
          afterIcon:
            type: static
            value: ''
          beforeIcon:
            type: static
            value: ''
          defaultValue:
            type: static
          disabled:
            type: static
            value: false
          placeholder:
            type: static
            value: Type...
        customCss:
          input:
            class: ''
            style: ''
        verticalAlignment: center
    - '12':
        fixed: false
        h: 1
        w: 2
        x: 5
        y: 11
      '3':
        fixed: false
        h: 1
        w: 1
        x: 2
        y: 0
      id: b
      data:
        id: b
        type: buttoncomponent
        actions: []
        componentInput:
          type: runnable
          autoRefresh: false
          fields:
            x:
              type: evalv2
              value: null
              connections:
                - id: result
                  componentId: a
              expr: a.result
              fieldType: string
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            type: runnableByName
            name: Inline Script 0
            inlineScript:
              content: '!inline inline_script_0.inline_script.py'
              lock: '!inline inline_script_0.inline_script.lock'
              language: python3
              path: u/donald/a_poc_to_validate_bulk_emails/Inline_Script_0
              schema:
                $schema: 'https://json-schema.org/draft/2020-12/schema'
                type: object
                properties:
                  x:
                    type: string
                    description: ''
                    default: null
                required:
                  - x
        configuration:
          afterIcon:
            type: static
            value: ''
          beforeIcon:
            type: static
            value: ''
          color:
            type: static
            value: blue
          confirmationModal:
            type: oneOf
            configuration:
              confirmationModal:
                description:
                  type: static
                  value: Are you sure?
                confirmationText:
                  type: static
                  value: Confirm
                title:
                  type: static
                  value: Title
              none: {}
            selected: none
          disabled:
            type: static
            value: false
          fillContainer:
            type: static
            value: false
          label:
            type: static
            value: Press me
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: errorOverlay
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: none
          size:
            type: static
            value: xs
          triggerOnAppLoad:
            type: static
            value: false
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
        verticalAlignment: center
    - '12':
        fixed: false
        h: 9
        w: 9
        x: 1
        y: 12
      '3':
        fixed: false
        h: 1
        w: 1
        x: 0
        y: 1
      id: c
      data:
        id: c
        type: textcomponent
        actions: []
        componentInput:
          type: evalv2
          connections:
            - id: result
              componentId: b
          eval: 'Hello ${ctx.username}'
          expr: "return `\r\nEmail Verification Results\r\n\r\nVerified Emails:\r\n${b.result[\"verified_emails\"].map(email => `- ${email}`).join('\\n')}\r\n\r\nTotal Verified Emails: ${b.result[\"verified_emails\"].length}\r\n\r\nGoogle Sheet URL: ${b.result[\"google_sheet_url\"]}\r\n`;"
          fieldType: template
        configuration:
          copyButton:
            type: static
            value: false
          style:
            type: static
            value: Body
          tooltip:
            type: static
            value: ''
        customCss:
          container:
            class: ''
            style: ''
          text:
            class: ''
            style: ''
        horizontalAlignment: left
        verticalAlignment: top
  hiddenInlineScripts: []
  norefreshbar: false
  subgrids: {}
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: anonymous
  triggerables_v2:
    'b:rawscript/aa1f978435d96697e564111906e302fd9a77774b99022e043ba4920978c192a3':
      one_of_inputs: {}
      static_inputs: {}
