# Generated by Django 5.1.1 on 2024-10-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace_users", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceuser",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceuser",
            unique_together={("user", "workspace")},
        ),
    ]
