# Generated by Django 5.1 on 2024-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apollo_people_search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apollopeoplesearch",
            name="name",
            field=models.CharField(default="unnamed", max_length=255),
            preserve_default=False,
        ),
    ]
