# Generated by Django 5.1.1 on 2024-09-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apollo_people_search", "0003_apollopeoplesearch_user"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apollopeoplesearch",
            unique_together={("name", "workspace")},
        ),
    ]
