# Generated by Django 5.1.1 on 2024-09-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workspace",
            name="users",
            field=models.ManyToManyField(
                related_name="workspaces",
                through="workspaces.WorkspaceUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
