# Generated by Django 5.1.1 on 2024-09-18 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace_users", "0001_initial"),
        ("workspaces", "0002_workspace_user_alter_workspace_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="users",
            field=models.ManyToManyField(
                related_name="workspaces",
                through="workspace_users.WorkspaceUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="WorkspaceUser",
        ),
    ]
