# Generated by Django 5.1 on 2024-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_workspace_public_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="workspace_public_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="workspaceuser",
            name="workspace_public_id",
            field=models.CharField(max_length=50),
        ),
    ]
