# Generated by Django 5.1.1 on 2024-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_workspace_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
