# Generated by Django 5.1.1 on 2024-09-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_alter_workspace_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="status",
            new_name="bootstrap_status",
        ),
    ]
