# Generated by Django 5.1.1 on 2024-09-29 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("functions", "0004_remove_function_version_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("input", "Input"), ("output", "Output")], max_length=6
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="functions.function",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
