# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("function_variables", "0006_functionvariable_function_call"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functionvariable",
            name="workspace",
        ),
    ]
