# Generated by Django 5.1 on 2024-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_rename_company_lead_company_domain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
