# Generated by Django 5.1 on 2024-08-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="workspace_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
