# Generated by Django 5.1 on 2024-08-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="created_by",
        ),
    ]
