# Generated by Django 5.1 on 2024-08-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_workspace_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="workspace_id",
            new_name="workspace_public_id",
        ),
    ]
