# Generated by Django 5.1 on 2024-08-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_remove_lead_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="lead",
            name="last_name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
