# Generated by Django 5.1 on 2024-08-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_rename_workspace_id_lead_workspace_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
    ]
