# Generated by Django 5.1 on 2024-08-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_rename_name_lead_first_name_lead_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="workspace_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
