# Generated by Django 5.1 on 2024-08-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_lead_linkedin_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="company_linkedin_url",
            field=models.URLField(blank=True),
        ),
    ]
