# Generated by Django 5.1 on 2024-08-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_lead_company_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="company_linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
