MODEL_WHITELIST = {
    "EmailAddress",
    "SocialApp",
    "SocialToken",
    "SocialAccount",
    "Group",
    "Site",
    "LogEntry",
    "Permission",
    "ContentType",
    "Session",
    "Workspace",
    "WorkspaceUser",
    "EmailConfirmation",
    "User",
    "Migration",
}

MODEL_ADMIN_WHITELIST = {
    "EmailAddress",
    "SocialApp",
    "SocialToken",
    "SocialAccount",
    "Group",
    "Site",
    "LogEntry",
    "Permission",
    "ContentType",
    "Session",
    "Workspace",
    "WorkspaceUser",
    "EmailConfirmation",
    "User",
    "APICall",
    "Migration",
}
