# Generated by Django 5.1 on 2024-09-02 17:56

import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("webhook_url", models.URLField()),
                ("payload", models.JSONField()),
                ("response_status", models.IntegerField()),
                ("response_content", models.TextField()),
            ],
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
