# Generated by Django 5.1 on 2024-09-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhook_tester", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingwebhook",
            name="url",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
    ]
