# Generated by Django 5.1 on 2024-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhook_tester", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhooktest",
            name="response_content",
        ),
        migrations.RemoveField(
            model_name="webhooktest",
            name="response_status",
        ),
    ]
