# Generated by Django 5.1 on 2024-09-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhook_tester", "0002_incomingwebhook_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebhookTest",
        ),
    ]
