# Generated by Django 5.1.1 on 2024-09-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gunicorn_instances", "0002_gunicorninstance_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gunicorninstance",
            old_name="pid",
            new_name="master_pid",
        ),
    ]
