# Generated by Django 5.1.1 on 2024-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gunicorn_instances", "0003_rename_pid_gunicorninstance_master_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gunicorninstance",
            name="master_pid",
            field=models.IntegerField(help_text="Process ID of the Gunicorn instance"),
        ),
    ]
