# Generated by Django 5.1.1 on 2024-09-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gunicorn_instances", "0004_alter_gunicorninstance_master_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="gunicorninstance",
            name="bootstrap_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
