# Generated by Django 5.1.1 on 2024-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gunicorn_instances", "0005_gunicorninstance_bootstrap_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gunicorninstance",
            name="bootstrap_status",
            field=models.CharField(
                choices=[
                    ("not started", "Not Started"),
                    ("pending", "Pending"),
                    ("done", "Done"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
