# Generated by Django 5.1.1 on 2024-09-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gunicorn_instances", "0006_alter_gunicorninstance_bootstrap_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gunicorninstance",
            name="bootstrap_status",
        ),
    ]
