// app/db/schema.ts

import {
  functionCalls,
  functionCallsRelations,
  functionCallStatusEnum,
  modelEnum,
  models,
  objects,
  objectsRelations,
  rawData,
  rawDataRelations,
  requests,
  requestsRelations,
  serverFunctions,
  serverFunctionsRelations,
  serverFunctionTypeEnum,
  sessions,
  sessionsRelations,
  TableModel,
  TABLES,
  users,
  usersRelations,
} from "./schema/index";

export {
  functionCalls,
  functionCallsRelations,
  functionCallStatusEnum,
  modelEnum,
  models,
  objects,
  objectsRelations,
  rawData,
  rawDataRelations,
  requests,
  requestsRelations,
  serverFunctions,
  serverFunctionsRelations,
  serverFunctionTypeEnum,
  sessions,
  sessionsRelations,
  TableModel,
  TABLES,
  users,
  usersRelations,
};

export const schema = {
  functionCalls,
  functionCallStatusEnum,
  modelEnum,
  models,
  objects,
  rawData,
  requests,
  serverFunctions,
  serverFunctionTypeEnum,
  sessions,
  users,
  relations: {
    functionCalls: functionCallsRelations,
    objects: objectsRelations,
    rawData: rawDataRelations,
    requests: requestsRelations,
    serverFunctions: serverFunctionsRelations,
    sessions: sessionsRelations,
    users: usersRelations,
  },
};
