# Generated by Django 5.1.1 on 2024-09-05 04:24

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_wizardstep_wizard"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WizardStepThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms.wizardstep",
                    ),
                ),
                (
                    "wizard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forms.wizard"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("wizard", "step")},
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="wizard",
            name="steps",
            field=models.ManyToManyField(
                through="forms.WizardStepThrough", to="forms.wizardstep"
            ),
        ),
    ]
