# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_data", "0003_delete_formdata"),
        ("forms", "0004_form_function_form_function_call"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Form",
        ),
    ]
