# Generated by Django 5.1.1 on 2024-09-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_wizardstepthrough_alter_wizard_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wizard",
            name="steps",
            field=models.ManyToManyField(to="forms.wizardstep"),
        ),
        migrations.DeleteModel(
            name="WizardStepThrough",
        ),
    ]
