# Generated by Django 5.1.1 on 2024-10-07 02:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0002_initial"),
        ("function_calls", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("singular_name", models.CharField(max_length=255)),
                ("plural_name", models.CharField(max_length=255)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model",
                        to="files.file",
                    ),
                ),
                (
                    "function_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="function_calls.functioncall",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
