# Generated by Django 5.1.1 on 2024-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
