# Generated by Django 5.1.1 on 2024-10-05 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
