# Generated by Django 5.1.1 on 2024-10-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_model_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="function",
        ),
    ]
