# Generated by Django 5.1.1 on 2024-09-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_model_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="content",
        ),
    ]
