# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0005_model_function_model_function_call"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="workspace",
        ),
    ]
