# Generated by Django 5.1.1 on 2024-09-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_remove_file_file"),
        ("models", "0005_remove_model_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="files.file",
            ),
        ),
    ]
