# Generated by Django 5.1.1 on 2024-09-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0006_alter_model_file"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="model",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="model",
            name="name",
        ),
    ]
