# Generated by Django 5.1 on 2024-08-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="workspace_public_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="apiprovider",
            name="workspace_public_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
