# Generated by Django 5.1 on 2024-09-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_providers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="public_id",
        ),
        migrations.RemoveField(
            model_name="apiprovider",
            name="public_id",
        ),
    ]
