# Generated by Django 5.1 on 2024-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_providers", "0002_apikey_workspace_public_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="workspace_public_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="apiprovider",
            name="workspace_public_id",
            field=models.CharField(max_length=50),
        ),
    ]
