# Generated by Django 5.1.1 on 2024-09-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_providers", "0003_apikey_user_apiprovider_user"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apiprovider",
            unique_together={("name", "workspace")},
        ),
    ]
