services:
  web:
    build: .
    command: python manage.py run_bluewind
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=appbluewinddb
      - DB_USERNAME=dbadmin
      - DB_PASSWORD=zYx8mQTqAe9r8A99thazK
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appbluewinddb
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=zYx8mQTqAe9r8A99thazK
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
