# Generated by Django 5.1.1 on 2024-09-29 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("functions", "0004_remove_function_version_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_relations",
                        to="functions.function",
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependency_relations",
                        to="functions.function",
                    ),
                ),
            ],
            options={
                "unique_together": {("dependent", "dependency")},
            },
        ),
    ]
