# Generated by Django 5.1.1 on 2024-09-29 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_call_dependencies", "0001_initial"),
        ("function_calls", "0008_remove_functioncall_input_data_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FunctionDependency",
            new_name="FunctionCallDependency",
        ),
        migrations.AlterField(
            model_name="functioncalldependency",
            name="dependency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependent_relations",
                to="function_calls.functioncall",
            ),
        ),
        migrations.AlterField(
            model_name="functioncalldependency",
            name="dependent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependency_relations",
                to="function_calls.functioncall",
            ),
        ),
    ]
