# Generated by Django 5.1.1 on 2024-10-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("function_call_dependencies", "0001_initial"),
        ("function_calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncalldependency",
            name="dependency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependent_relations",
                to="function_calls.functioncall",
            ),
        ),
        migrations.AddField(
            model_name="functioncalldependency",
            name="dependent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependency_relations",
                to="function_calls.functioncall",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="functioncalldependency",
            unique_together={("dependent", "dependency")},
        ),
    ]
