# Generated by Django 5.1.1 on 2024-09-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "function_call_dependencies",
            "0002_rename_functiondependency_functioncalldependency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncalldependency",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
