# Generated by Django 5.1.1 on 2024-10-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_call_dependencies", "0002_initial"),
        ("function_calls", "0005_functioncall_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncalldependency",
            name="function_call",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="function_calls.functioncall",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="functioncalldependency",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
