# Generated by Django 5.1.1 on 2024-09-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_call_dependencies", "0003_functioncalldependency_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncalldependency",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
