# Generated by Django 5.1.1 on 2024-09-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_watchers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filewatcher",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("shutting-down", "Shutting Down"),
                    ("terminated", "Terminated"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
