# Generated by Django 5.1.1 on 2024-09-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_watchers", "0002_filewatcher_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="filewatcher",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="filewatcher",
            name="name",
        ),
    ]
