# Generated by Django 5.1.1 on 2024-09-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("action_runs", "0001_initial"),
        ("flows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminevent",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_runs",
                to="flows.action",
            ),
        ),
    ]
