# Generated by Django 5.1.1 on 2024-09-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_runs", "0002_initial"),
        ("recordings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionrun",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_runs",
                to="recordings.recording",
            ),
        ),
    ]
