summary: ''
value:
  css: {}
  fullscreen: false
  grid:
    - '12':
        fixed: false
        h: 21
        w: 12
        x: 0
        y: 0
      '3':
        fixed: false
        h: 8
        w: 2
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: verticalsplitpanescomponent
        configuration: {}
        customCss: {}
        numberOfSubgrids: 2
        panes:
          - 50
          - 50
  hiddenInlineScripts: []
  norefreshbar: false
  subgrids:
    a-0:
      - '12':
          fixed: false
          h: 19
          w: 12
          x: 0
          y: 0
        '3':
          fixed: false
          h: 8
          w: 3
          x: 0
          y: 1
        id: c
        data:
          id: c
          type: schemaformcomponent
          componentInput:
            type: static
            value:
              $schema: 'https://json-schema.org/draft/2020-12/schema'
              type: object
              properties: {}
              required: []
            fieldType: schema
          configuration:
            defaultValues:
              type: static
            displayType:
              type: static
              value: false
            dynamicEnums:
              type: static
            largeGap:
              type: static
              value: false
          customCss: {}
      - '12':
          fixed: false
          h: 1
          w: 12
          x: 0
          y: 19
        '3':
          fixed: false
          h: 1
          w: 1
          x: 0
          y: 0
        id: d
        data:
          id: d
          type: buttoncomponent
          componentInput:
            type: runnable
            autoRefresh: false
            fields: {}
            fieldType: any
            recomputeOnInputChanged: false
            runnable:
              type: runnableByPath
              name: u/admin/basic_end_to_end
              path: u/admin/basic_end_to_end
              runType: flow
              schema:
                $schema: 'https://json-schema.org/draft/2020-12/schema'
                type: object
                properties: {}
                required: []
          configuration:
            afterIcon:
              type: static
              value: ''
            beforeIcon:
              type: static
              value: ''
            color:
              type: static
              value: dark
            disabled:
              type: eval
              expr: '!c.valid'
            fillContainer:
              type: static
              value: false
            label:
              type: static
              value: Submit
            onError:
              type: oneOf
              configuration:
                close:
                  id:
                    type: static
                    value: ''
                closeModal:
                  modalId:
                    type: static
                    value: ''
                errorOverlay: {}
                gotoUrl:
                  newTab:
                    type: static
                    value: true
                  url:
                    type: static
                    value: ''
                open:
                  id:
                    type: static
                    value: ''
                openModal:
                  modalId:
                    type: static
                    value: ''
                sendErrorToast:
                  appendError:
                    type: static
                    value: true
                  message:
                    type: static
                    value: ''
                setTab:
                  setTab:
                    type: static
                    value: []
              selected: errorOverlay
            onSuccess:
              type: oneOf
              configuration:
                close:
                  id:
                    type: static
                    value: ''
                closeModal:
                  modalId:
                    type: static
                    value: ''
                gotoUrl:
                  newTab:
                    type: static
                    value: true
                  url:
                    type: static
                    value: ''
                none: {}
                open:
                  id:
                    type: static
                    value: ''
                openModal:
                  modalId:
                    type: static
                    value: ''
                sendToast:
                  message:
                    type: static
                    value: ''
                setTab:
                  setTab:
                    type: static
                    value: []
              selected: none
            size:
              type: static
              value: xs
            triggerOnAppLoad:
              type: static
              value: false
          customCss: {}
          horizontalAlignment: right
          recomputeIds: []
          verticalAlignment: center
    a-1:
      - '12':
          fixed: false
          h: 20
          w: 12
          x: 0
          y: 0
        '3':
          fixed: false
          h: 8
          w: 2
          x: 0
          y: 0
        id: b
        data:
          id: b
          type: tabscomponent
          configuration:
            tabsKind:
              type: static
              value: tabs
          customCss: {}
          disabledTabs:
            - type: static
              value: false
              fieldType: boolean
            - type: static
              value: false
              fieldType: boolean
          numberOfSubgrids: 2
          tabs:
            - Result
            - Logs
    b-0:
      - '12':
          fixed: false
          h: 18
          w: 12
          x: 0
          y: 0
        '3':
          fixed: false
          h: 8
          w: 2
          x: 0
          y: 0
        id: e
        data:
          id: e
          type: jobidflowstatuscomponent
          configuration:
            jobId:
              type: connected
              value: ''
              connection:
                componentId: d
                path: jobId
          customCss: {}
    b-1:
      - '12':
          fixed: false
          h: 18
          w: 12
          x: 0
          y: 0
        '3':
          fixed: false
          h: 8
          w: 2
          x: 0
          y: 0
        id: f
        data:
          id: f
          type: jobidlogcomponent
          configuration:
            jobId:
              type: connected
              connection:
                componentId: d
                path: jobId
          customCss: {}
  unusedInlineScripts: []
policy:
  execution_mode: anonymous
  triggerables_v2:
    'd:flow/u/admin/basic_end_to_end':
      one_of_inputs: {}
      static_inputs: {}
