# Generated by Django 5.0.7 on 2024-07-31 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspace',
            table=None,
        ),
        migrations.CreateModel(
            name='WorkspaceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('user', 'workspace')},
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(through='workspaces.WorkspaceUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
