# Generated by Django 5.1.1 on 2024-09-20 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diff_related_entities", "0001_initial"),
        ("workspace_diffs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diffrelatedentities",
            name="diff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_entities",
                to="workspace_diffs.workspacediff",
            ),
        ),
        migrations.AddField(
            model_name="diffrelatedentities",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
