# Generated by Django 5.0.8.dev20240802093154 on 2024-08-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="public_id",
        ),
    ]
