# Generated by Django 5.1 on 2024-08-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="gmail_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("workspace_public_id", "gmail_message_id")},
        ),
    ]
