# Generated by Django 5.1 on 2024-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_remove_message_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
