# Generated by Django 5.1 on 2024-08-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="gmail_message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
