# Generated by Django 5.1 on 2024-08-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="sender",
            new_name="channel",
        ),
    ]
