# Generated by Django 5.1.1 on 2024-09-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0003_initial"),
        ("people", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="people.person",
            ),
            preserve_default=False,
        ),
    ]
