# Generated by Django 5.1 on 2024-09-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="public_id",
        ),
    ]
