# Generated by Django 5.1.1 on 2024-09-26 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("functions", "0002_alter_function_unique_together"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("conditions-not-met", "Conditions Not Met"),
                            ("ready-for-approval", "Ready for Approval"),
                            ("approved", "Approved"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            (
                                "completed-waiting-for-approval",
                                "Completed Waiting for Approval",
                            ),
                            ("marked-successful", "Marked Successful"),
                            ("marked-failed", "Marked Failed"),
                            ("successful", "Successful"),
                        ],
                        default="conditions-not-met",
                        max_length=35,
                    ),
                ),
                ("state", models.JSONField(default=dict)),
                ("input_data", models.JSONField(blank=True, null=True)),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="functions.function",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="function_calls.functioncall",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
