# Generated by Django 5.1.1 on 2024-10-07 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FunctionCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("conditions-not-met", "Conditions Not Met"),
                            ("ready-for-approval", "Ready for Approval"),
                            ("requires-human-input", "Requires Human Input"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            (
                                "completed-ready-for-approval",
                                "Completed Ready for Approval",
                            ),
                            ("marked-successful", "Marked Successful"),
                            ("marked-failed", "Marked Failed"),
                            ("successful", "Successful"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="conditions-not-met",
                        max_length=35,
                    ),
                ),
                ("state", models.JSONField(default=dict)),
                ("input_parameter_name", models.CharField(max_length=255)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                (
                    "output_type",
                    models.CharField(choices=[("queryset", "queryset")], max_length=35),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("remaining_dependencies", models.IntegerField(default=0)),
                ("thoughts", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
