# Generated by Django 5.1.1 on 2024-09-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("form_data", "0002_initial"),
        ("function_calls", "0001_initial"),
        ("functions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="functions.function"
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="input_form_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="function_calls_using_as_input",
                to="form_data.formdata",
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="output_form_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="function_calls_using_as_output",
                to="form_data.formdata",
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="tn_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tn_children",
                to="function_calls.functioncall",
                verbose_name="Parent",
            ),
        ),
    ]
