# Generated by Django 5.1.1 on 2024-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functioncall",
            name="output_data",
        ),
        migrations.AlterField(
            model_name="functioncall",
            name="input_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
