# Generated by Django 5.1.1 on 2024-10-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("function_calls", "0001_initial"),
        ("functions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_calls",
                to="functions.function",
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="function_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="function_calls.functioncall",
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="output_data_dependency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_calls_related_output",
                to="function_calls.functioncall",
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="function_calls.functioncall",
            ),
        ),
    ]
