# Generated by Django 5.1.1 on 2024-09-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0003_functioncall_long_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functioncall",
            name="long_description",
        ),
        migrations.AddField(
            model_name="functioncall",
            name="thoughts",
            field=models.TextField(
                blank=True,
                help_text="Any thoughts or notes about this function call",
                null=True,
            ),
        ),
    ]
