# Generated by Django 5.1.1 on 2024-10-04 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="output_data_dependency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_calls_related_output",
                to="function_calls.functioncall",
            ),
        ),
    ]
