# Generated by Django 5.1.1 on 2024-09-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0004_remove_functioncall_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functioncall",
            name="thoughts",
            field=models.TextField(blank=True, null=True),
        ),
    ]
