# Generated by Django 5.1.1 on 2024-10-05 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0004_functioncall_output_data_dependency"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
