# Generated by Django 5.1.1 on 2024-09-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functioncall",
            name="is_root",
        ),
        migrations.AddField(
            model_name="functioncall",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendants",
                to="function_calls.functioncall",
            ),
        ),
    ]
