# Generated by Django 5.1.1 on 2024-09-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0005_alter_functioncall_thoughts"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="output_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
