# Generated by Django 5.1.1 on 2024-09-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0005_remove_functioncall_is_root_functioncall_root"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functioncall",
            name="whole_tree",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
