# Generated by Django 5.1.1 on 2024-09-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
        ("function_calls", "0006_functioncall_output_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="input_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="input_function_calls",
                to="forms.form",
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="output_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="output_function_calls",
                to="forms.form",
            ),
        ),
    ]
