# Generated by Django 5.1.1 on 2024-09-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_data", "0002_rename_input_data_formdata_data"),
        ("function_calls", "0007_functioncall_input_form_functioncall_output_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functioncall",
            name="input_data",
        ),
        migrations.RemoveField(
            model_name="functioncall",
            name="input_form",
        ),
        migrations.RemoveField(
            model_name="functioncall",
            name="output_data",
        ),
        migrations.RemoveField(
            model_name="functioncall",
            name="output_form",
        ),
        migrations.AddField(
            model_name="functioncall",
            name="input_form_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="function_calls_using_as_input",
                to="form_data.formdata",
            ),
        ),
        migrations.AddField(
            model_name="functioncall",
            name="input_parameter_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="functioncall",
            name="output_form_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="function_calls_using_as_output",
                to="form_data.formdata",
            ),
        ),
    ]
