# Generated by Django 5.1.1 on 2024-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0009_functioncall_remaining_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="output_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
