# Generated by Django 5.1.1 on 2024-10-01 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0011_functioncall_function_call_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functioncall",
            name="function_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="function_calls.functioncall",
            ),
        ),
    ]
