# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0012_alter_functioncall_function_call"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functioncall",
            name="input_form_data",
        ),
        migrations.RemoveField(
            model_name="functioncall",
            name="output_form_data",
        ),
        migrations.RemoveField(
            model_name="functioncall",
            name="workspace",
        ),
    ]
