# Generated by Django 5.1.1 on 2024-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0012_alter_functioncall_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="input_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
