# Generated by Django 5.1.1 on 2024-09-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0013_functioncall_input_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="functioncall",
            name="output_type",
            field=models.CharField(
                choices=[
                    ("conditions-not-met", "Conditions Not Met"),
                    ("ready-for-approval", "Ready for Approval"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("completed-ready-for-approval", "Completed Ready for Approval"),
                    ("marked-successful", "Marked Successful"),
                    ("marked-failed", "Marked Failed"),
                    ("successful", "Successful"),
                ],
                default=1,
                max_length=35,
            ),
            preserve_default=False,
        ),
    ]
