# Generated by Django 5.1.1 on 2024-10-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0013_remove_functioncall_input_form_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functioncall",
            name="whole_tree",
        ),
    ]
