# Generated by Django 5.1.1 on 2024-09-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0015_alter_functioncall_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functioncall",
            name="parent",
        ),
    ]
