summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: false
        h: 15
        w: 12
        x: 0
        y: 0
      '3':
        fixed: false
        h: 5
        w: 3
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: formcomponent
        actions: []
        componentInput:
          type: runnable
          autoRefresh: false
          fields:
            company_name:
              type: user
              value: Bluewind
              fieldType: string
              format: ''
            custom_taglines:
              type: user
              value:
                - open-source automations to grow your business
                - free automations to grow your business
              fieldType: array
              format: ''
            domain_name:
              type: user
              value: bluewind(.)ai
              fieldType: string
              format: ''
            sender_first_name:
              type: user
              value: Wayne
              fieldType: string
              format: ''
            sender_last_name:
              type: user
              value: Hamadi
              fieldType: string
              format: ''
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            type: runnableByPath
            name: Generate signatures
            path: u/admin/thankful_flow
            runType: flow
            schema:
              $schema: 'https://json-schema.org/draft/2020-12/schema'
              type: object
              order:
                - company_name
                - domain_name
                - sender_first_name
                - sender_last_name
                - custom_taglines
              properties:
                company_name:
                  type: string
                  description: ''
                  default: Bluewind
                  format: ''
                  password: false
                custom_taglines:
                  type: array
                  description: ''
                  default:
                    - open-source automations to grow your business
                    - free automations to grow your business
                  format: ''
                  items:
                    type: string
                domain_name:
                  type: string
                  description: ''
                  default: bluewind(.)ai
                  format: ''
                  password: false
                sender_first_name:
                  type: string
                  description: ''
                  default: Wayne
                  format: ''
                sender_last_name:
                  type: string
                  description: ''
                  default: Hamadi
                  format: ''
                  password: false
              required: []
        configuration:
          color:
            type: static
            value: dark
          label:
            type: static
            value: Submit
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: An error occured
              setTab:
                setTab:
                  type: static
                  value: []
            selected: errorOverlay
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: none
          size:
            type: static
            value: xs
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
    - '12':
        fixed: false
        h: 12
        w: 12
        x: 0
        y: 15
      '3':
        fixed: false
        h: 8
        w: 3
        x: 0
        y: 5
      id: b
      data:
        id: b
        type: schemaformcomponent
        actions: []
        componentInput:
          type: static
          value:
            order:
              - picked_signature
              - signatures
            properties:
              picked_signature:
                type: string
                description: your name
                default: default
                password: false
              signatures:
                type: array
                description: ''
                default: []
                items:
                  type: string
            required: []
          fieldType: schema
        configuration:
          defaultValues:
            type: evalv2
            value: {}
            connections:
              - id: result
                componentId: a
            expr: |-
              return {
                "picked_signature": a.result["picked_signature"],
                "signatures": a.result["signatures"]
              }
          displayType:
            type: static
            value: false
          dynamicEnums:
            type: static
            value: {}
          largeGap:
            type: static
            value: false
        customCss:
          description:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
          label:
            class: ''
            style: ''
  hiddenInlineScripts: []
  norefreshbar: false
  subgrids: {}
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: anonymous
  triggerables_v2:
    'a:flow/u/admin/thankful_flow':
      one_of_inputs: {}
      static_inputs: {}
