# Generated by Django 5.1.1 on 2024-10-07 04:09

import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("function_calls", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("key", models.CharField(max_length=255)),
                (
                    "value",
                    encrypted_fields.fields.EncryptedCharField(max_length=100000),
                ),
                (
                    "function_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="function_calls.functioncall",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Credentials",
            },
        ),
    ]
