# Generated by Django 5.1.1 on 2024-10-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="key",
            field=models.CharField(
                choices=[("apollo-api-key", "Apollo API Key")],
                default="apollo-api-key",
                max_length=255,
            ),
        ),
    ]
