# Generated by Django 5.1 on 2024-09-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentials",
            name="is_base64",
            field=models.BooleanField(default=False, verbose_name="Convert to Base64"),
        ),
    ]
