# Generated by Django 5.1.1 on 2024-10-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0002_rename_credentials_credential"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credential",
            options={},
        ),
    ]
