# Generated by Django 5.1 on 2024-09-03 03:47

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0003_alter_credentials_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="value",
            field=encrypted_fields.fields.EncryptedCharField(max_length=2000),
        ),
    ]
