# Generated by Django 5.1 on 2024-09-03 03:53

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0005_remove_credentials_is_base64_alter_credentials_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="value",
            field=encrypted_fields.fields.EncryptedCharField(max_length=100000),
        ),
    ]
