# Generated by Django 5.1 on 2024-09-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="workspace_public_id",
        ),
    ]
