# Generated by Django 5.1.1 on 2024-09-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstep",
            name="default_values",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
