# Generated by Django 5.1.1 on 2024-09-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionrun",
            name="flow_run",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_runs",
                to="flows.flowrun",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="StepRun",
        ),
    ]
