# Generated by Django 5.1.1 on 2024-09-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0003_actionrun_flow_run_actionrun_status_delete_steprun"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="action_run",
        ),
        migrations.AddField(
            model_name="action",
            name="flow",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="flows.flow",
            ),
            preserve_default=False,
        ),
    ]
