# Generated by Django 5.1.1 on 2024-09-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="app",
        ),
    ]
