# Generated by Django 5.1.1 on 2024-09-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0003_alter_action_action_type_alter_flowstep_action_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="workspace",
        ),
        migrations.AlterField(
            model_name="action",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("SAVE", "Save"),
                    ("DELETE", "Delete"),
                    ("ACTION", "Action"),
                    ("SELECT", "Select"),
                    ("LIST_VIEW", "List View"),
                ],
                max_length=20,
            ),
        ),
    ]
