# Generated by Django 5.1.1 on 2024-09-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0003_remove_actionrun_data_actionrun_results"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("name", "app_label", "workspace")},
        ),
    ]
