# Generated by Django 5.1.1 on 2024-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0004_alter_model_unique_together"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="is_recorded",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("workspace", "action_type", "model")},
        ),
    ]
