# Generated by Django 5.1.1 on 2024-09-09 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0004_remove_action_workspace_alter_action_action_type"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
    ]
