# Generated by Django 5.1.1 on 2024-09-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0004_alter_flowrun_user"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flow",
            unique_together={("name", "workspace")},
        ),
        migrations.AlterUniqueTogether(
            name="recording",
            unique_together={("name", "workspace")},
        ),
    ]
