# Generated by Django 5.1.1 on 2024-09-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0004_remove_action_action_run_action_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionrun",
            name="action_input",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
