# Generated by Django 5.1.1 on 2024-09-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0002_initial"),
        ("flows", "0004_action_flowstep_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="admin_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="admin_events.adminevent",
            ),
        ),
    ]
