# Generated by Django 5.1.1 on 2024-09-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("flows", "0004_flowrunargument"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flowrunargument",
            old_name="content_type",
            new_name="contenttype",
        ),
        migrations.AlterUniqueTogether(
            name="flowrunargument",
            unique_together={("flow_run", "contenttype", "object_id")},
        ),
    ]
