# Generated by Django 5.1.1 on 2024-09-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0005_actionrun_action_input"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlowStep",
        ),
    ]
