# Generated by Django 5.1.1 on 2024-09-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0005_rename_content_type_flowrunargument_contenttype_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlowRunArgument",
        ),
    ]
