# Generated by Django 5.1.1 on 2024-09-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0006_flowrun_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="description",
        ),
        migrations.AddField(
            model_name="flow",
            name="git_sha",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
