# Generated by Django 5.1.1 on 2024-09-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0006_delete_flowrunargument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steprun",
            name="action_run",
        ),
        migrations.AlterUniqueTogether(
            name="flow",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="flow",
            name="user",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="step",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="diff",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="user",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="steprun",
            name="flow_run",
        ),
        migrations.RemoveField(
            model_name="step",
            name="action",
        ),
        migrations.RemoveField(
            model_name="step",
            name="parent_step",
        ),
        migrations.RemoveField(
            model_name="step",
            name="user",
        ),
        migrations.RemoveField(
            model_name="step",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="steprun",
            name="step",
        ),
        migrations.RemoveField(
            model_name="steprun",
            name="user",
        ),
        migrations.RemoveField(
            model_name="steprun",
            name="workspace",
        ),
        migrations.DeleteModel(
            name="ActionRun",
        ),
        migrations.DeleteModel(
            name="Flow",
        ),
        migrations.DeleteModel(
            name="FlowRun",
        ),
        migrations.DeleteModel(
            name="Step",
        ),
        migrations.DeleteModel(
            name="StepRun",
        ),
    ]
