# Generated by Django 5.1.1 on 2024-09-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0007_step_actionrun_step"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={},
        ),
        migrations.RemoveField(
            model_name="step",
            name="order",
        ),
    ]
