# Generated by Django 5.1.1 on 2024-09-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0007_remove_flow_description_flow_git_sha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="git_sha",
        ),
    ]
