# Generated by Django 5.1.1 on 2024-09-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0008_remove_flow_git_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="diff_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
