# Generated by Django 5.1.1 on 2024-09-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0008_alter_step_options_remove_step_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("SAVE", "Save"),
                    ("DELETE", "Delete"),
                    ("CUSTOM", "Custom"),
                    ("LIST", "List"),
                    ("SHOW", "Show"),
                ],
                max_length=20,
            ),
        ),
    ]
