# Generated by Django 5.1.1 on 2024-09-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0008_flow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Action",
        ),
    ]
