# Generated by Django 5.1.1 on 2024-09-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0009_delete_action"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recording",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="recording",
            name="user",
        ),
        migrations.RemoveField(
            model_name="recording",
            name="workspace",
        ),
    ]
