# Generated by Django 5.1.1 on 2024-09-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0009_alter_action_action_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="action_input",
        ),
        migrations.RemoveField(
            model_name="action",
            name="flow",
        ),
    ]
