# Generated by Django 5.1.1 on 2024-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0009_flowrun_diff_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="type",
            field=models.CharField(
                choices=[("no-code", "No Code"), ("python", "Python")],
                default="no-code",
                max_length=10,
            ),
        ),
    ]
