# Generated by Django 5.1.1 on 2024-09-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0010_flow_type"),
        ("workspace_snapshots", "0004_diffrelatedentities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="diff_id",
        ),
        migrations.AddField(
            model_name="flowrun",
            name="diff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flow_runs",
                to="workspace_snapshots.workspacediff",
            ),
        ),
    ]
