# Generated by Django 5.1.1 on 2024-09-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("action_runs", "0003_alter_actionrun_recording"),
        ("flows", "0010_alter_recording_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recording",
        ),
    ]
