# Generated by Django 5.1.1 on 2024-09-10 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0010_remove_action_action_input_remove_action_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionrun",
            name="flow_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flows.flowrun",
            ),
        ),
    ]
