# Generated by Django 5.1.1 on 2024-09-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0011_remove_flowrun_diff_id_flowrun_diff"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="create_new_workspace",
            field=models.BooleanField(default=False),
        ),
    ]
