# Generated by Django 5.1.1 on 2024-09-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0012_steprun_actionrun_step_run"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionrun",
            name="flow_run",
        ),
        migrations.RemoveField(
            model_name="actionrun",
            name="step",
        ),
    ]
