# Generated by Django 5.1.1 on 2024-09-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_remove_file_file"),
        ("flows", "0013_flow_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flows",
                to="files.file",
            ),
        ),
    ]
