# Generated by Django 5.1.1 on 2024-09-10 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0013_remove_actionrun_flow_run_remove_actionrun_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="steprun",
            name="flow_run",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_runs",
                to="flows.flowrun",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="steprun",
            name="action_run",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_step_run",
                to="flows.actionrun",
            ),
        ),
        migrations.AlterField(
            model_name="steprun",
            name="step",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_runs",
                to="flows.step",
            ),
        ),
    ]
