# Generated by Django 5.1.1 on 2024-09-18 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_remove_app_singular_name"),
        ("files", "0004_remove_file_file"),
        ("flows", "0014_alter_flow_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="app",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow",
                to="apps.app",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flow",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow",
                to="files.file",
            ),
        ),
    ]
