# Generated by Django 5.1.1 on 2024-09-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0015_alter_steprun_action_run_alter_steprun_flow_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steprun",
            name="flow_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_runs",
                to="flows.flowrun",
            ),
        ),
        migrations.AlterField(
            model_name="steprun",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_runs",
                to="flows.step",
            ),
        ),
    ]
