# Generated by Django 5.1.1 on 2024-09-18 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_remove_file_file"),
        ("flows", "0015_flow_app_alter_flow_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="file",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow",
                to="files.file",
            ),
            preserve_default=False,
        ),
    ]
