# Generated by Django 5.1.1 on 2024-09-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supervisord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_file",
                    models.FilePathField(
                        match=".*\\.conf$",
                        max_length=255,
                        path="/etc/supervisor/conf.d/",
                        recursive=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("shutting-down", "Shutting Down"),
                            ("terminated", "Terminated"),
                        ],
                        default="terminated",
                        max_length=20,
                    ),
                ),
                ("last_action_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
