# Generated by Django 5.1.1 on 2024-09-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supervisord", "0002_supervisord_user_supervisord_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supervisord",
            name="config_file",
        ),
    ]
