# Generated by Django 5.1.1 on 2024-09-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("step_runs", "0001_initial"),
        ("steps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="steprun",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_runs",
                to="steps.step",
            ),
        ),
    ]
