# Generated by Django 5.1.1 on 2024-09-20 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_watchers", "0003_alter_filewatcher_unique_together_and_more"),
        ("workspaces", "0007_alter_workspace_bootstrap_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileSystemChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        help_text="The path of the file that was changed.",
                        max_length=255,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("modified", "Modified"),
                            ("deleted", "Deleted"),
                        ],
                        help_text="Type of change detected (e.g., modified, created, deleted).",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the change was detected.",
                    ),
                ),
                (
                    "file_watcher",
                    models.ForeignKey(
                        help_text="The file watcher that detected this change.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_system_changes",
                        to="file_watchers.filewatcher",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user responsible for the file change, if known.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
