# Generated by Django 5.1.1 on 2024-09-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_system_changes", "0001_initial"),
        ("file_watchers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesystemchange",
            name="file_watcher",
            field=models.ForeignKey(
                help_text="The file watcher that detected this change.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_system_changes",
                to="file_watchers.filewatcher",
            ),
        ),
    ]
