# Generated by Django 5.1.1 on 2024-09-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_system_changes", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesystemchange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("modified", "Modified"),
                    ("deleted", "Deleted"),
                    ("moved", "Moved"),
                ],
                help_text="Type of change detected (e.g., modified, created, deleted).",
                max_length=50,
            ),
        ),
    ]
