# Generated by Django 5.1.1 on 2024-09-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_system_changes", "0005_alter_filesystemchange_change_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesystemchange",
            name="destination",
            field=models.CharField(
                blank=True,
                help_text="The destination path for moved files.",
                max_length=255,
                null=True,
            ),
        ),
    ]
