# Generated by Django 5.1.1 on 2024-09-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_system_changes", "0006_filesystemchange_destination"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filesystemchange",
            old_name="destination",
            new_name="destination_path",
        ),
    ]
