# Generated by Django 5.1.1 on 2024-09-07 04:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminevent",
            name="data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
