# Generated by Django 5.1.1 on 2024-09-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="steprun",
            name="input_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
