# Generated by Django 5.1.1 on 2024-09-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0003_steprun_input_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steprun",
            name="input_data",
        ),
    ]
