# Generated by Django 5.1.1 on 2024-09-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0003_steprun_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="steprun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="steprun",
            name="flow_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_runs",
                to="admin_events.flowstep",
            ),
        ),
    ]
