# Generated by Django 5.1.1 on 2024-09-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0004_steprun_status_alter_steprun_flow_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
