# Generated by Django 5.1.1 on 2024-09-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0005_flowrun_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowstep",
            name="form",
        ),
    ]
