# Generated by Django 5.1.1 on 2024-09-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0005_steprun_input_data"),
        ("forms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstep",
            name="form",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_steps",
                to="forms.form",
            ),
            preserve_default=False,
        ),
    ]
