# Generated by Django 5.1.1 on 2024-09-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0005_flow_flowstep"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flowstep",
            options={},
        ),
        migrations.RemoveField(
            model_name="flowstep",
            name="order",
        ),
        migrations.AddField(
            model_name="flowstep",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="admin_events.flowstep",
            ),
        ),
    ]
