# Generated by Django 5.1.1 on 2024-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0006_alter_flowstep_options_remove_flowstep_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowstep",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("SAVE", "Save"),
                    ("DELETE", "Delete"),
                    ("ACTION", "Action"),
                    ("SELECT", "Select"),
                ],
                default="ACTION",
                max_length=10,
            ),
        ),
    ]
