# Generated by Django 5.1.1 on 2024-09-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0006_remove_flowstep_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowstep",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="steprun",
            name="flow_run",
        ),
        migrations.RemoveField(
            model_name="flowstep",
            name="model",
        ),
        migrations.RemoveField(
            model_name="flowstep",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="steprun",
            name="flow_step",
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="model",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="steprun",
            name="workspace",
        ),
        migrations.DeleteModel(
            name="Flow",
        ),
        migrations.DeleteModel(
            name="FlowRun",
        ),
        migrations.DeleteModel(
            name="FlowStep",
        ),
        migrations.DeleteModel(
            name="Model",
        ),
        migrations.DeleteModel(
            name="StepRun",
        ),
    ]
