# Generated by Django 5.1.1 on 2024-09-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0009_remove_flowstep_model_name_model_flowstep_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={"ordering": ["app_label", "name"]},
        ),
        migrations.AddField(
            model_name="model",
            name="app_label",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("app_label", "name")},
        ),
    ]
