# Generated by Django 5.1.1 on 2024-09-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0010_alter_model_options_model_app_label_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowstep",
            name="parent",
        ),
        migrations.AlterField(
            model_name="flowstep",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="flowstep",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="model",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workspaces.workspace",
            ),
        ),
    ]
