# Generated by Django 5.1.1 on 2024-09-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0011_remove_flowstep_parent_alter_flowstep_action_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowstep",
            name="action",
        ),
        migrations.AddField(
            model_name="flowstep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("SAVE", "Save"),
                    ("DELETE", "Delete"),
                    ("ACTION", "Action"),
                    ("SELECT", "Select"),
                ],
                default="ACTION",
                max_length=10,
            ),
        ),
    ]
