# Generated by Django 5.1.1 on 2024-09-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_events", "0014_steprun"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
