# Generated by Django 5.1.1 on 2024-10-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("function_calls", "0011_functioncall_function_call_and_more"),
        ("functions", "0004_function_function_function_function_call_and_more"),
        ("test_inlines", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="function",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="functions.function",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="function_call",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="function_calls.functioncall",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="function",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="functions.function",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="function_call",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="function_calls.functioncall",
            ),
            preserve_default=False,
        ),
    ]
