# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_inlines",
            "0004_author_function_author_function_call_book_function_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="workspace",
        ),
        migrations.RemoveField(
            model_name="book",
            name="workspace",
        ),
    ]
