# Generated by Django 5.1.1 on 2024-09-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("logger_name", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=20)),
                ("sql", models.TextField(max_length=10000)),
                ("params", models.TextField(blank=True, max_length=1000, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                (
                    "database_alias",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("app_label", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
