# Generated by Django 5.1.1 on 2024-09-12 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_logs", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="querylog",
            name="database_alias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="params",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="sql",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspaces.workspace",
            ),
        ),
    ]
