# Generated by Django 5.1.1 on 2024-09-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_logs", "0002_alter_querylog_database_alias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="app_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
