# Generated by Django 5.1 on 2024-09-02 02:39

import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GmailSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("project_id", models.CharField(max_length=100)),
                ("topic_id", models.CharField(max_length=100)),
                ("push_endpoint", models.URLField()),
                ("label_ids", models.JSONField(default=list)),
                (
                    "label_filter_action",
                    models.CharField(default="include", max_length=20),
                ),
                ("client_secret_file", models.CharField(max_length=255)),
                ("oauth_scopes", models.JSONField(default=list)),
                ("redirect_uri", models.URLField()),
            ],
            options={
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
