# Generated by Django 5.1.1 on 2024-09-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pubsubtopic",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="pubsubtopic",
            name="user",
        ),
        migrations.RemoveField(
            model_name="pubsubtopic",
            name="workspace",
        ),
    ]
