# Generated by Django 5.1 on 2024-09-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credentials",
        ),
    ]
