# Generated by Django 5.1 on 2024-09-03 02:15

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_subscriptions", "0003_remove_gmailsubscription_public_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    encrypted_fields.fields.EncryptedCharField(max_length=255),
                ),
                (
                    "client_secret",
                    encrypted_fields.fields.EncryptedCharField(max_length=255),
                ),
                ("refresh_token", encrypted_fields.fields.EncryptedTextField()),
                (
                    "token_uri",
                    models.URLField(default="https://oauth2.googleapis.com/token"),
                ),
                ("scopes", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
