# Generated by Django 5.1.1 on 2024-09-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_subscriptions", "0003_alter_pubsubtopic_unique_together_and_more"),
        ("pub_sub_topics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmailsubscription",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pub_sub_topics.pubsubtopic",
            ),
        ),
        migrations.DeleteModel(
            name="PubSubTopic",
        ),
    ]
