# Generated by Django 5.1.1 on 2024-10-06 02:39

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("function_calls", "0005_functioncall_created_at"),
        ("functions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApolloCompanySearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="An array of organization ids obtained from companies-search",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "organization_num_employees_ranges",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1-10", "1-10"),
                                ("11-50", "11-50"),
                                ("51-200", "51-200"),
                                ("201-500", "201-500"),
                                ("501-1000", "501-1000"),
                                ("1001-5000", "1001-5000"),
                                ("5001-10000", "5001-10000"),
                                ("10001+", "10001+"),
                            ],
                            max_length=20,
                        ),
                        help_text="Intervals to include organizations having number of employees in a range",
                        size=None,
                    ),
                ),
                (
                    "organization_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="An array of strings denoting allowed locations of organization headquarters",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "organization_not_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="An array of strings denoting un-allowed locations of organization headquarters",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "q_organization_keyword_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        help_text="An array of strings denoting the keywords an organization should be associated with",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "prospected_by_current_team",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=3),
                        blank=True,
                        help_text="An array of string booleans defining whether we want models prospected by current team or not",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "q_organization_name",
                    models.CharField(
                        blank=True,
                        help_text="A string representing the name of the organization we want to filter",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="An integer that allows you to paginate through the results",
                    ),
                ),
                (
                    "per_page",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="An integer to load per_page results on a page. Should be in inclusive range [1, 100]",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="functions.function",
                    ),
                ),
                (
                    "function_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="function_calls.functioncall",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Apollo Company Search",
                "verbose_name_plural": "Apollo Company Searches",
            },
        ),
    ]
