# Generated by Django 5.1.1 on 2024-10-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apollo_company_searches", "0001_initial"),
        ("function_calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apollocompanysearch",
            name="function_call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="function_calls.functioncall",
            ),
        ),
    ]
