# Generated by Django 5.1.1 on 2024-10-05 23:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apollo_company_searches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apollocompanysearch",
            name="organization_num_employees_ranges",
        ),
        migrations.DeleteModel(
            name="EmployeeRange",
        ),
        migrations.AddField(
            model_name="apollocompanysearch",
            name="organization_num_employees_ranges",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("1-10", "1-10"),
                        ("11-50", "11-50"),
                        ("51-200", "51-200"),
                        ("201-500", "201-500"),
                        ("501-1000", "501-1000"),
                        ("1001-5000", "1001-5000"),
                        ("5001-10000", "5001-10000"),
                        ("10001+", "10001+"),
                    ],
                    max_length=20,
                ),
                blank=True,
                help_text="Intervals to include organizations having number of employees in a range",
                null=True,
                size=None,
            ),
        ),
    ]
