# Generated by Django 5.1.1 on 2024-09-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channel_wizzard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChannelWizard",
        ),
    ]
