# Generated by Django 5.1.1 on 2024-10-06 02:48

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("function_calls", "0005_functioncall_created_at"),
        ("functions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=253, unique=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization_num_employees_ranges",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1-10", "1-10"),
                                ("11-50", "11-50"),
                                ("51-200", "51-200"),
                                ("201-500", "201-500"),
                                ("501-1000", "501-1000"),
                                ("1001-5000", "1001-5000"),
                                ("5001-10000", "5001-10000"),
                                ("10001+", "10001+"),
                            ],
                            max_length=20,
                        ),
                        help_text="Intervals to include organizations having number of employees in a range",
                        size=None,
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="functions.function",
                    ),
                ),
                (
                    "function_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_names",
                        to="function_calls.functioncall",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
