# Generated by Django 5.1.1 on 2024-10-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_names", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainname",
            name="organization_num_employees_ranges",
        ),
    ]
