# Generated by Django 5.1.1 on 2024-10-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domain_names", "0001_initial"),
        ("function_calls", "0001_initial"),
        ("functions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainname",
            name="function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="functions.function"
            ),
        ),
        migrations.AddField(
            model_name="domainname",
            name="function_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_names",
                to="function_calls.functioncall",
            ),
        ),
    ]
