# Generated by Django 5.1.1 on 2024-09-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_names", "0002_domainname_user_domainname_workspace_and_more"),
        ("function_calls", "0008_remove_functioncall_input_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainname",
            name="function_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_names",
                to="function_calls.functioncall",
            ),
        ),
    ]
