# Generated by Django 5.1.1 on 2024-10-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_names", "0002_remove_domainname_organization_num_employees_ranges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainname",
            name="function",
        ),
    ]
