# Generated by Django 5.1.1 on 2024-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_names", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainname",
            name="last_scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
