# Generated by Django 5.1.1 on 2024-10-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain_names", "0004_initial"),
        ("functions", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainname",
            name="function",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="functions.function",
            ),
            preserve_default=False,
        ),
    ]
