# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain_names", "0005_domainname_function"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="domainname",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="domainname",
            name="workspace",
        ),
    ]
