# Generated by Django 5.1.1 on 2024-09-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='workspace',
        ),
    ]
