# Generated by Django 5.1.1 on 2024-09-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncomingHTTPRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
