summary: generate subject lines
value:
  fullscreen: false
  grid:
    - '12':
        fixed: false
        h: 8
        w: 12
        x: 0
        y: 0
      '3':
        fixed: false
        h: 5
        w: 3
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: formcomponent
        actions: []
        componentInput:
          type: runnable
          autoRefresh: false
          fields:
            recipient_company_name:
              type: user
              value: Leadbird
              fieldType: string
              format: ''
            recipient_first_name:
              type: user
              value: Nick Abraham
              fieldType: string
              format: ''
            sender_company_name:
              type: user
              value: Superagent
              fieldType: string
              format: ''
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            type: runnableByPath
            name: u/admin/magic_flow
            path: u/admin/magic_flow
            runType: flow
            schema:
              $schema: 'https://json-schema.org/draft/2020-12/schema'
              type: object
              order:
                - recipient_first_name
                - recipient_company_name
                - sender_company_name
              properties:
                recipient_company_name:
                  type: string
                  description: ''
                  default: Leadbird
                  format: ''
                  password: false
                recipient_first_name:
                  type: string
                  description: ''
                  default: Nick Abraham
                  format: ''
                  password: false
                sender_company_name:
                  type: string
                  description: ''
                  default: Superagent
                  format: ''
                  password: false
              required: []
        configuration:
          color:
            type: static
            value: dark
          label:
            type: static
            value: Submit
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: errorOverlay
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: none
          size:
            type: static
            value: xs
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
    - '12':
        fixed: false
        h: 12
        w: 12
        x: 0
        y: 8
      '3':
        fixed: false
        h: 8
        w: 3
        x: 0
        y: 5
      id: b
      data:
        id: b
        type: schemaformcomponent
        actions: []
        componentInput:
          type: static
          value:
            order:
              - subject_lines
            properties:
              subject_lines:
                type: array
                description: your name
                default: []
                items:
                  type: string
            required: []
          fieldType: schema
        configuration:
          defaultValues:
            type: evalv2
            connections:
              - id: result
                componentId: a
            expr: |-
              return {
                "subject_lines": a.result["subject_lines"]
              }
          displayType:
            type: static
            value: false
          dynamicEnums:
            type: static
            value: {}
          largeGap:
            type: static
            value: false
        customCss:
          description:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
          label:
            class: ''
            style: ''
  hiddenInlineScripts: []
  norefreshbar: false
  subgrids: {}
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: anonymous
  triggerables_v2:
    'a:flow/u/admin/magic_flow':
      one_of_inputs: {}
      static_inputs: {}
