# Generated by Django 5.1.1 on 2024-09-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("form_data", "0001_initial"),
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdata",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_data",
                to="forms.form",
            ),
        ),
    ]
