# Generated by Django 5.1.1 on 2024-09-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formdata",
            old_name="input_data",
            new_name="data",
        ),
    ]
