# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_data", "0002_initial"),
        ("function_calls", "0013_remove_functioncall_input_form_data_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormData",
        ),
    ]
