# Generated by Django 5.1 on 2024-08-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("email", "workspace")},
        ),
    ]
