# Generated by Django 5.1 on 2024-09-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
