# Generated by Django 5.1 on 2024-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alter_person_first_name_alter_person_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="workspace_public_id",
            field=models.CharField(max_length=50),
        ),
    ]
