# Generated by Django 5.1.1 on 2024-10-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("function_calls", "0001_initial"),
        ("functions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="function",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="functions.function",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="function_call",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="function_calls.functioncall",
            ),
        ),
    ]
