# Generated by Django 5.1.1 on 2024-09-15 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_rename_filemodel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.ForeignKey(
                default=1,
                help_text="The file that was changed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="files.file",
            ),
            preserve_default=False,
        ),
    ]
