# Generated by Django 5.1.1 on 2024-09-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_file_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file",
        ),
    ]
