# Generated by Django 5.1.1 on 2024-10-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_file_function_alter_file_function_call"),
        ("function_calls", "0012_alter_functioncall_function_call"),
        ("functions", "0004_function_function_function_function_call_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="function",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="functions.function",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="function_call",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="function_calls.functioncall",
            ),
        ),
    ]
