# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_alter_file_function_alter_file_function_call"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="file",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="file",
            name="workspace",
        ),
    ]
