# Generated by Django 5.1 on 2024-08-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inboxes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="last_checked",
        ),
    ]
