# Generated by Django 5.1 on 2024-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inboxes", "0003_inbox_workspace_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbox",
            name="workspace_public_id",
            field=models.CharField(max_length=50),
        ),
    ]
