# Generated by Django 5.0.8.dev20240802093154 on 2024-08-05 01:06

import public_id.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DBGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    public_id.models.PublicIDField(editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Database Graph",
                "managed": False,
            },
        ),
    ]
