# Generated by Django 5.1.1 on 2024-09-15 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_changes", "0001_initial"),
        ("file_watchers", "0001_initial"),
        ("workspaces", "0002_workspace_user_alter_workspace_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FileChanged",
            new_name="FileChange",
        ),
    ]
