# Generated by Django 5.1.1 on 2024-09-16 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_changes", "0002_rename_filechanged_filechange"),
        ("files", "0004_remove_file_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filechange",
            name="file_path",
        ),
        migrations.AddField(
            model_name="filechange",
            name="file",
            field=models.ForeignKey(
                default=1,
                help_text="The file that was changed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="files.file",
            ),
            preserve_default=False,
        ),
    ]
