# Generated by Django 5.1.1 on 2024-09-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_changes", "0003_remove_filechange_file_path_filechange_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filechange",
            name="file",
        ),
        migrations.AddField(
            model_name="filechange",
            name="source_path",
            field=models.CharField(
                default=1,
                help_text="The path of the file that was changed.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
