# Generated by Django 5.1.1 on 2024-09-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_changes", "0004_remove_filechange_file_filechange_source_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filechange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("modified", "Modified"),
                    ("deleted", "Deleted"),
                ],
                help_text="Type of change detected (e.g., modified, created, deleted).",
                max_length=50,
            ),
        ),
    ]
