summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: false
        h: 1
        w: 2
        x: 0
        y: 0
      '3':
        fixed: false
        h: 1
        w: 2
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: textinputcomponent
        actions: []
        configuration:
          afterIcon:
            type: static
            value: ''
          beforeIcon:
            type: static
            value: ''
          defaultValue:
            type: static
          disabled:
            type: static
            value: false
          placeholder:
            type: static
            value: Type...
        customCss:
          input:
            class: ''
            style: ''
        verticalAlignment: center
  hiddenInlineScripts: []
  norefreshbar: false
  subgrids: {}
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: publisher
  triggerables_v2: {}
