# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_entity_function_entity_function_call"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="entity",
            name="workspace",
        ),
    ]
