# Generated by Django 5.1.1 on 2024-10-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="function",
        ),
    ]
