# Generated by Django 5.1.1 on 2024-09-10 00:09

import encrypted_fields.fields
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "access_token",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1000, null=True
                    ),
                ),
                (
                    "refresh_token",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1000, null=True
                    ),
                ),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "client_id",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1000, null=True
                    ),
                ),
                (
                    "client_secret",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=1000, null=True
                    ),
                ),
                ("last_history_id", models.TextField(blank=True, null=True)),
                ("watch_expiration", models.DateTimeField(blank=True, null=True)),
            ],
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
