# Generated by Django 5.1 on 2024-08-29 20:55

import bluewind.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=bluewind.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_public_id", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
