# Generated by Django 5.1 on 2024-09-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
