# Generated by Django 5.1 on 2024-09-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="last_history_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="watch_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
