# Generated by Django 5.1 on 2024-08-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("workspace_public_id", "email")},
        ),
    ]
