# Generated by Django 5.1 on 2024-09-04 00:39

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_initial"),
        ("gmail_subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="gmail_subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gmail_subscriptions.gmailsubscription",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="channel",
            name="access_token",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="client_id",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="client_secret",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="refresh_token",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
    ]
