# Generated by Django 5.1.1 on 2024-09-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0002_initial"),
        ("gmail_subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="gmail_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gmail_subscriptions.gmailsubscription",
            ),
        ),
    ]
