# Generated by Django 5.1 on 2024-08-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_channel_gmail_expiration_channel_gmail_history_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
