# Generated by Django 5.1 on 2024-09-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0003_channel_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="token",
            new_name="access_token",
        ),
        migrations.RenameField(
            model_name="channel",
            old_name="last_synced",
            new_name="token_expiry",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="gmail_expiration",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="gmail_history_id",
        ),
        migrations.AddField(
            model_name="channel",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
