# Generated by Django 5.1 on 2024-09-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_channel_gmail_subscription_and_more"),
        ("gmail_subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="gmail_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gmail_subscriptions.gmailsubscription",
            ),
        ),
    ]
