# Generated by Django 5.1 on 2024-09-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0004_alter_channel_gmail_subscription"),
        ("credentials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="gmail_credentials",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="credentials.credentials",
            ),
            preserve_default=False,
        ),
    ]
