# Generated by Django 5.1.1 on 2024-09-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
