summary: Benin Republic Local Languages To Image
value:
  css:
    alertcomponent:
      description:
        class: ''
        style: ''
      background:
        class: ''
        style: ''
      container:
        class: ''
        style: ''
      icon:
        class: ''
        style: ''
      title:
        class: ''
        style: ''
    horizontaldividercomponent:
      container:
        class: ''
        style: ''
      divider:
        class: ''
        style: ''
        tooltip: >-
          `background-color` and `height` are handled by the component
          configuration
    selectcomponent:
      input:
        class: ''
        style: ''
        tooltip: >-
          https://github.com/rob-balfre/svelte-select/blob/master/docs/theming_variables.md
    verticalsplitpanescomponent:
      container:
        class: ''
        style: ''
  fullscreen: false
  grid:
    - '12':
        fixed: false
        h: 1
        w: 3
        x: 5
        y: 2
      '3':
        fixed: false
        h: 1
        w: 2
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: selectcomponent
        actions: []
        configuration:
          create:
            type: static
            value: false
          defaultValue:
            type: static
          disabled:
            type: static
            value: false
          fullWidth:
            type: static
            value: true
          items:
            type: static
            value:
              - value: yo
                label: Yoruba
              - value: fr
                label: French
          placeholder:
            type: static
            value: Select a language
          preselectFirst:
            type: static
            value: true
        customCss:
          input:
            class: ''
            style: ''
            tooltip: >-
              https://github.com/rob-balfre/svelte-select/blob/master/docs/theming_variables.md
        recomputeIds: []
        verticalAlignment: center
    - '12':
        fixed: false
        h: 1
        w: 3
        x: 5
        y: 4
      '3':
        fixed: false
        h: 1
        w: 2
        x: 0
        y: 1
      id: b
      data:
        id: b
        type: textinputcomponent
        actions: []
        configuration:
          afterIcon:
            type: static
            value: ''
          beforeIcon:
            type: static
            value: ''
          defaultValue:
            type: static
          disabled:
            type: static
            value: false
          placeholder:
            type: static
            value: Type...
        customCss:
          input:
            class: ''
            style: ''
        verticalAlignment: center
    - '12':
        fixed: false
        h: 1
        w: 3
        x: 5
        y: 6
      '3':
        fixed: false
        h: 1
        w: 1
        x: 2
        y: 0
      id: c
      data:
        id: c
        type: buttoncomponent
        actions: []
        componentInput:
          type: runnable
          autoRefresh: false
          fields:
            data:
              type: evalv2
              connections:
                - id: result
                  componentId: b
                - id: result
                  componentId: a
              expr: "return {\r\n  \"language\": a.result,\r\n  \"prompt\": b.result\r\n}"
              fieldType: object
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            type: runnableByName
            name: Inline Script 0
            inlineScript:
              content: '!inline inline_script_0.inline_script.py'
              lock: '!inline inline_script_0.inline_script.lock'
              language: python3
              path: >-
                u/donald/benin_republic_local_languages_translator/Inline_Script_0
              schema:
                $schema: 'https://json-schema.org/draft/2020-12/schema'
                type: object
                properties:
                  data:
                    type: object
                    description: ''
                    default: null
                    properties: {}
                required:
                  - data
        configuration:
          afterIcon:
            type: static
            value: ''
          beforeIcon:
            type: static
            value: ''
          color:
            type: static
            value: blue
          confirmationModal:
            type: oneOf
            configuration:
              confirmationModal:
                description:
                  type: static
                  value: Are you sure?
                confirmationText:
                  type: static
                  value: Confirm
                title:
                  type: static
                  value: Title
              none: {}
            selected: none
          disabled:
            type: static
            value: false
          fillContainer:
            type: static
            value: false
          label:
            type: static
            value: Press me
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: An error occured
              setTab:
                setTab:
                  type: static
                  value: []
            selected: sendErrorToast
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: Translation Successful!
              setTab:
                setTab:
                  type: static
                  value: []
            selected: sendToast
          size:
            type: static
            value: xs
          triggerOnAppLoad:
            type: static
            value: false
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
        verticalAlignment: center
    - '12':
        fixed: false
        h: 1
        w: 12
        x: 0
        y: 7
      '3':
        fixed: false
        h: 1
        w: 3
        x: 0
        y: 3
      id: e
      data:
        id: e
        type: horizontaldividercomponent
        actions: []
        configuration:
          color:
            type: static
            value: '#00000060'
          size:
            type: static
            value: 2
        customCss:
          container:
            class: ''
            style: ''
          divider:
            class: ''
            style: ''
            tooltip: >-
              `background-color` and `height` are handled by the component
              configuration
        verticalAlignment: center
    - '12':
        fixed: false
        h: 4
        w: 5
        x: 4
        y: 8
      '3':
        fixed: false
        h: 4
        w: 3
        x: 0
        y: 4
      id: f
      data:
        id: f
        type: imagecomponent
        actions: []
        configuration:
          altText:
            type: static
            value: Generated Image
          imageFit:
            type: static
            value: contain
          source:
            type: evalv2
            value: ''
            connections:
              - id: result
                componentId: c
            expr: return c.result.image_url;
          sourceKind:
            type: static
            value: url
        customCss:
          image:
            class: ''
            style: ''
  hiddenInlineScripts: []
  norefreshbar: false
  subgrids: {}
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: anonymous
  triggerables_v2:
    'c:rawscript/f1a74b77c1c7eb09694f4912dbec70f2d89d6c6c2e81919c750bab1a880a661b':
      one_of_inputs: {}
      static_inputs: {}
