# Generated by Django 5.1.1 on 2024-09-13 22:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incoming_http_requests", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("level", models.CharField(max_length=10)),
                ("logger", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "incoming_http_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incoming_http_requests.incominghttprequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["incoming_http_request"],
                        name="app_logs_ap_incomin_b22412_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="app_logs_ap_timesta_4a73d8_idx"
                    ),
                ],
            },
        ),
    ]
