# Generated by Django 5.1.1 on 2024-09-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_logs", "0001_initial"),
        ("incoming_http_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applog",
            name="incoming_http_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incoming_http_requests.incominghttprequest",
            ),
        ),
    ]
