# Generated by Django 5.1.1 on 2024-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_logs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applog",
            name="traceback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
