# Generated by Django 5.1.1 on 2024-09-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_logs", "0003_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applog",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workspaces.workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="applog",
            index=models.Index(
                fields=["incoming_http_request"], name="app_logs_ap_incomin_b22412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applog",
            index=models.Index(
                fields=["timestamp"], name="app_logs_ap_timesta_4a73d8_idx"
            ),
        ),
    ]
