# Generated by Django 5.1 on 2024-09-03 19:41

import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Base64Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("output_text", models.TextField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("encode", "Encode to Base64"),
                            ("decode", "Decode from Base64"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Base64 Conversion",
                "verbose_name_plural": "Base64 Conversions",
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
