# Generated by Django 5.1.1 on 2024-09-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base64_utils", "0003_base64conversion_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="base64conversion",
            name="output_text",
            field=models.TextField(blank=True),
        ),
    ]
