# Generated by Django 5.1.1 on 2024-09-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="singular_name",
        ),
    ]
