# Generated by Django 5.1.1 on 2024-10-07 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="@",
                        help_text="Subdomain or '@' for apex",
                        max_length=253,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("MX", "MX"), ("TXT", "TXT")], max_length=10
                    ),
                ),
                ("value", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        help_text="Priority for MX records",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
            ],
        ),
    ]
