# Generated by Django 5.1.1 on 2024-10-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domain_names", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Subdomain or empty for apex",
                        max_length=253,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("MX", "MX"), ("TXT", "TXT")], max_length=10
                    ),
                ),
                ("value", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        blank=True, help_text="Priority for MX records", null=True
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_records",
                        to="domain_names.domainname",
                    ),
                ),
            ],
        ),
    ]
