# Generated by Django 5.1.1 on 2024-10-05 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dns_records", "0001_initial"),
        ("domain_names", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(
                default="@", help_text="Subdomain or '@' for apex", max_length=253
            ),
        ),
        migrations.AlterField(
            model_name="dnsrecord",
            name="priority",
            field=models.IntegerField(
                blank=True,
                help_text="Priority for MX records",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dnsrecord",
            unique_together={
                ("domain", "name", "record_type"),
                ("domain", "name", "record_type", "value", "priority"),
            },
        ),
        migrations.AddIndex(
            model_name="dnsrecord",
            index=models.Index(
                fields=["domain", "name", "record_type"],
                name="dns_records_domain__55e74d_idx",
            ),
        ),
    ]
