# Generated by Django 5.1.1 on 2024-10-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dns_records", "0002_alter_dnsrecord_name_alter_dnsrecord_priority_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dnsrecord",
            name="dns_records_domain__55e74d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="dnsrecord",
            unique_together=set(),
        ),
    ]
