# Generated by Django 5.1.1 on 2024-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dns_records",
            "0003_remove_dnsrecord_dns_records_domain__55e74d_idx_and_more",
        ),
        ("domain_names", "0004_domainname_last_scanned_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dnsrecord",
            index=models.Index(
                fields=["domain", "name", "record_type", "value"],
                name="dns_records_domain__35b1a9_idx",
            ),
        ),
    ]
