# Generated by Django 5.1.1 on 2024-10-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dns_records", "0004_dnsrecord_dns_records_domain__35b1a9_idx"),
        ("domain_names", "0004_domainname_last_scanned_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dnsrecord",
            name="dns_records_domain__35b1a9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="dnsrecord",
            unique_together={("domain", "name", "record_type", "value", "priority")},
        ),
    ]
