summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: false
        h: 12
        w: 12
        x: 0
        y: 0
      '3':
        fixed: false
        h: 5
        w: 3
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: formcomponent
        actions: []
        componentInput:
          type: runnable
          autoRefresh: false
          fields:
            hubspot_access_token:
              type: user
              value: ''
              fieldType: string
              format: ''
            hubspot_contacts:
              type: user
              value:
                - id: '21974040595'
                  archived: false
                  createdAt: '2024-05-16T17:47:42.133Z'
                  properties:
                    createdate: '2024-05-16T17:47:42.133Z'
                    email: jackie@retool.com
                    hs_object_id: '21974040595'
                    is_catch_all: null
                    is_email_valid: null
                    lastmodifieddate: '2024-05-16T17:47:58.883Z'
                    linkedin_url: 'http://www.linkedin.com/in/jackie-karmel-27358030'
                  updatedAt: '2024-05-16T17:47:58.883Z'
                - id: '21971565664'
                  archived: false
                  createdAt: '2024-05-16T17:47:42.134Z'
                  properties:
                    createdate: '2024-05-16T17:47:42.134Z'
                    email: alvinberger@lifesenseproducts.com
                    hs_object_id: '21971565664'
                    is_catch_all: null
                    is_email_valid: null
                    lastmodifieddate: '2024-05-16T17:48:08.448Z'
                    linkedin_url: 'http://www.linkedin.com/in/alvin-berger-41a8211'
                  updatedAt: '2024-05-16T17:48:08.448Z'
              fieldType: array
              format: ''
            leadmagic_api_key:
              type: user
              value: ''
              fieldType: string
              format: ''
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            type: runnableByPath
            name: iterate through hubspot contacts
            path: u/admin/incredible_flow_fork
            runType: flow
            schema:
              $schema: 'https://json-schema.org/draft/2020-12/schema'
              type: object
              order:
                - leadmagic_api_key
                - hubspot_access_token
                - hubspot_contacts
              properties:
                hubspot_access_token:
                  type: string
                  description: ''
                  default: ''
                  format: ''
                  password: true
                hubspot_contacts:
                  type: array
                  description: ''
                  default:
                    - id: '21974040595'
                      archived: false
                      createdAt: '2024-05-16T17:47:42.133Z'
                      properties:
                        createdate: '2024-05-16T17:47:42.133Z'
                        email: jackie@retool.com
                        hs_object_id: '21974040595'
                        is_catch_all: null
                        is_email_valid: null
                        lastmodifieddate: '2024-05-16T17:47:58.883Z'
                        linkedin_url: 'http://www.linkedin.com/in/jackie-karmel-27358030'
                      updatedAt: '2024-05-16T17:47:58.883Z'
                    - id: '21971565664'
                      archived: false
                      createdAt: '2024-05-16T17:47:42.134Z'
                      properties:
                        createdate: '2024-05-16T17:47:42.134Z'
                        email: alvinberger@lifesenseproducts.com
                        hs_object_id: '21971565664'
                        is_catch_all: null
                        is_email_valid: null
                        lastmodifieddate: '2024-05-16T17:48:08.448Z'
                        linkedin_url: 'http://www.linkedin.com/in/alvin-berger-41a8211'
                      updatedAt: '2024-05-16T17:48:08.448Z'
                  format: ''
                  items:
                    type: object
                leadmagic_api_key:
                  type: string
                  description: ''
                  default: ''
                  format: ''
                  password: true
              required: []
        configuration:
          color:
            type: static
            value: dark
          label:
            type: static
            value: Submit
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: An error occured
              setTab:
                setTab:
                  type: static
                  value: []
            selected: errorOverlay
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: none
          size:
            type: static
            value: xs
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
  hiddenInlineScripts: []
  norefreshbar: false
  subgrids: {}
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: publisher
  triggerables_v2:
    'a:flow/u/admin/incredible_flow_fork':
      one_of_inputs: {}
      static_inputs: {}
