# Generated by Django 5.1.1 on 2024-09-15 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_runs", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="create_new_workspace",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="diff",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="state",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="status",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="flowrun",
            name="executed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="result",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="input_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
