# Generated by Django 5.1.1 on 2024-09-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_runs", "0003_remove_flowrun_create_new_workspace_and_more"),
        ("flows", "0011_delete_recording"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="user",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="workspace",
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flows.flow"
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="input_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="result",
            field=models.TextField(blank=True, null=True),
        ),
    ]
