# Generated by Django 5.1.1 on 2024-09-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_runs", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="status",
            field=models.CharField(default="PENDING", max_length=50),
        ),
    ]
