# Generated by Django 5.1.1 on 2024-09-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_runs", "0005_flowrun_user_flowrun_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="output_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
