# Generated by Django 5.1.1 on 2024-09-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_runs", "0006_flowrun_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("conditions-not-met", "Conditions Not Met"),
                    ("ready", "READY"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                ],
                default="conditions-not-met",
                max_length=20,
            ),
        ),
    ]
