# Generated by Django 5.1.1 on 2024-09-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow_runs", "0008_alter_flowrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="flow_runs.flowrun",
            ),
        ),
    ]
