name: 'Push main to Windmill workspace'
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - windmill/**

env:
  WMILL_URL: https://bluewind.windmill.dev/
  WMILL_WORKSPACE: bluewind

jobs:
  sync:
    environment: windmill
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.43.5

      # (push will pull first to detect conflicts and only push actual changes)
      - name: Push changes
        run: |
          cd windmill
          deno run --unstable -A  https://deno.land/x/wmill@v1.333.4/main.ts workspace add __automation ${{ env.WMILL_WORKSPACE }} ${{ env.WMILL_URL }} --token ${{ secrets.WMILL_TOKEN }}
          deno run --unstable -A  https://deno.land/x/wmill@v1.333.4/main.ts sync push --yes --raw --skip-variables --skip-secrets --skip-resources
          deno run --unstable -A  https://deno.land/x/wmill@v1.333.4/main.ts workspace add __devautomation devbluewind ${{ env.WMILL_URL }} --token ${{ secrets.WMILL_TOKEN }}
          deno run --unstable -A  https://deno.land/x/wmill@v1.333.4/main.ts sync push --yes --raw --skip-variables --skip-secrets --skip-resources
