"on":
  push:
    branches:
    - main
name: Deploy to bluewind-proxy
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./.github/workflows/porter.yaml
      env:
        PORTER_CLUSTER: "3741"
        PORTER_DEPLOYMENT_TARGET_ID: 206795df-c745-43b1-bb7c-adfd2b41d954
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_PROJECT: "11978"
        PORTER_STACK_NAME: bluewind-proxy
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_11978_3741 }}
