# Generated by Django 5.1.1 on 2024-09-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace_diffs", "0001_initial"),
        ("workspace_snapshots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diffrelatedentities",
            name="diff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_entities",
                to="workspace_diffs.workspacediff",
            ),
        ),
        migrations.DeleteModel(
            name="WorkspaceDiff",
        ),
    ]
