# Generated by Django 5.1.1 on 2024-09-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workspace_snapshots",
            "0002_alter_diffrelatedentities_diff_delete_workspacediff",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiffRelatedEntities",
        ),
    ]
