# Generated by Django 5.1.1 on 2024-09-19 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daphne_processes", "0001_initial"),
        ("workspaces", "0007_alter_workspace_bootstrap_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GunicornInstance",
            new_name="DaphneProcess",
        ),
    ]
