# Generated by Django 5.1.1 on 2024-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daphne_processes", "0002_rename_gunicorninstance_daphneprocess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daphneprocess",
            name="master_pid",
            field=models.IntegerField(help_text="Process ID of the Daphne process"),
        ),
    ]
