# Generated by Django 5.1.1 on 2024-09-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="function",
            unique_together={("name", "workspace")},
        ),
    ]
