# Generated by Django 5.1.1 on 2024-09-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0002_alter_function_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="version_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
