# Generated by Django 5.1.1 on 2024-09-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0003_function_version_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="function",
            name="version_number",
        ),
    ]
