# Generated by Django 5.1.1 on 2024-10-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_file_function_file_function_call"),
        ("function_calls", "0011_functioncall_function_call_and_more"),
        ("functions", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_functions",
                to="functions.function",
            ),
        ),
        migrations.AddField(
            model_name="function",
            name="function_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_functions",
                to="function_calls.functioncall",
            ),
        ),
        migrations.AlterField(
            model_name="function",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_function",
                to="files.file",
            ),
        ),
    ]
