# Generated by Django 5.1.1 on 2024-10-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0004_function_function_function_function_call_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="function",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="function",
            name="workspace",
        ),
    ]
